//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorksOfConsole.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbVisitEntities : DbContext
    {
        public DbVisitEntities()
            : base("name=DbVisitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblCountry> TblCountry { get; set; }
        public virtual DbSet<TblFlight> TblFlight { get; set; }
        public virtual DbSet<TblPerson> TblPerson { get; set; }
        public virtual DbSet<FlightDetails> FlightDetails { get; set; }
    }
}
